kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carbide-dsx-exchange-consumer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: carbide-dsx-exchange-consumer
subjects:
  - kind: ServiceAccount
    name: carbide-dsx-exchange-consumer
    namespace: default
